services:
  product:
    platform: linux/amd64
    build: microservices/product-service
    image: product
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  recommendation:
    platform: linux/amd64
    build: microservices/recommendation-service
    image: recommendation
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  review:
    platform: linux/amd64
    build: microservices/review-service
    image: review
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  product-composite:
    platform: linux/amd64
    build: microservices/product-composite-service
    image: product-composite
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - target: 8080
        published: 8080

  eureka:
    platform: linux/amd64
    build: spring-cloud/eureka-server
    mem_limit: 512m
    ports:
      - target: 8761
        published: 8761

  mongodb:
    image: mongo:4.4.11
    mem_limit: 512m
    ports:
      - "27017:27017"
    command: mongod
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 5s
      timeout: 2s
      retries: 60

  mariadb:
    image: mariadb:10.7.1
    ports:
      - target: 3306
        published: 3308
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=review-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd