server:
  port: 7001
  error:
    include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db
  auto-index-creation: true

spring.application.name: product

app.eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

logging:
  level:
    root: INFO
    com.trungnguyen.microservices: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring.config.activate.on-profile: docker
app.eureka-server: eureka

server.port: 8080
spring:
  data:
    mongodb:
      host: mongodb

